if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(c("graph", "RBGL"))

install.packages("fields")
install.packages("/causal-discovery/gptk_1.08.tar.gz", repos = NULL, type="source", dependencies=TRUE)
install.packages("mgcv")
install.packages("pcalg")
install.packages("kpcalg")
install.packages("RCIT")
install.packages("kernlab")
install.packages("igraph")
install.packages("parallel")
install.packages("clue")
install.packages("mboost")
install.packages("fastICA")
install.packages("glmnet")

install.packages("remotes")
library(remotes)
install.packages("MASS")
install.packages("momentchi2")

BiocManager::install(c("igraph"), Ncpus=4)
install.packages("pcalg")
install.packages("kpcalg")
install_github("Diviyan-Kalainathan/RCIT")

install.packages("reticulate")